name: harvestly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Icon/AddIcon.png
    - assets/Icon/BackIcon.png
    - assets/Icon/FilterIcon.png
    - assets/Icon/HeartFullIcon.png
    - assets/Icon/HeartLessIcon.png
    - assets/images/Apple.jpg
    - assets/images/Banana.jpg
    - assets/images/Blueberry.png
    - assets/images/Grape.jpg
    - assets/images/Kiwi.png
    - assets/images/Lemon.jpg
    - assets/images/Peach.jpg
    - assets/images/watermelon.png
